//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gripper.Utils.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gripper.Utils.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.250.79.153,34.241.213.33,52.31.128.198,54.194.74.105,3.248.208.62,3.250.75.156,18.203.234.209,3.250.194.186,52.212.40.189,54.171.106.69,34.250.159.102,3.251.86.234,52.16.146.90,3.250.124.189,54.195.128.146,34.245.81.87,3.250.49.102,34.244.105.201,52.30.38.34,54.72.208.8,34.245.119.11,34.244.13.54,34.240.158.138,54.171.139.243,54.75.113.249,54.154.213.232,34.248.144.27,52.50.76.104,34.244.104.128,54.171.241.142,18.202.57.84,176.34.77.177,52.214.170.17,3.250.218.20,3.251.70.251,34.245.93.217,34.252.53.39,54 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Proxies {
            get {
                return ResourceManager.GetString("Proxies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 808.
        /// </summary>
        internal static string ProxyPort {
            get {
                return ResourceManager.GetString("ProxyPort", resourceCulture);
            }
        }
    }
}
