# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "build"
  build:
    name: build, pack & publish
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
    - name: checkout
      uses: actions/checkout@v2
      
    - name: Setup 5.0.x .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Pack
      run: dotnet pack --configuration="Release"
      
    - name: Add github source to nuget
      run: dotnet nuget add source --username ${{ github.repository_owner }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
      
    - name: Publish Gripper.WebClient to github
      run: dotnet nuget push ${{ github.workspace }}/Gripper.WebClient/bin/Release/Gripper.WebClient.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source github
    
    - name: Publish Gripper.WebClient.Cdtr to github
      run: dotnet nuget push ${{ github.workspace }}/Gripper.WebClient.Cdtr/bin/Release/Gripper.WebClient.Cdtr.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source github
    
    - name: Publish Gripper.WebClient to nuget gallery
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
        # Filepath of the project to be packaged, relative to root of repository
        PROJECT_FILE_PATH: ${{ github.workspace }}/Gripper.WebClient/Gripper.WebClient.csproj
        PACKAGE_NAME: 'Gripper.WebClient'
        NUGET_KEY: ${{secrets.NUGET_KEY}}
        NUGET_SOURCE: 'https://api.nuget.org'
        
    - name: Publish to nuget gallery
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
        # Filepath of the project to be packaged, relative to root of repository
        PROJECT_FILE_PATH: ${{ github.workspace }}/Gripper.WebClient.Cdtr/Gripper.WebClient.Cdtr.csproj
        PACKAGE_NAME: 'Gripper.WebClient.Cdtr'
        NUGET_KEY: ${{secrets.NUGET_KEY}}
        NUGET_SOURCE: 'https://api.nuget.org'
      
